### ISSUE TITLE
I got a error when I was running train.py

### ISSUE THREAD

**Issue by Ciciluang** [SvipRepetitionCounting/TransRAC#10]
the error is"RuntimeError:stack expects each tensor to be equal size,but got [3,420,224,224] at entry 0 and [3,299,224,224] at entry 1",I think maybe there is some problem in data pocessing,could you tell me how to deal with it if you don't mind,thankyou very much.

**Comment by Ironieser** [comment]
I guess the two data in the same batch have a different number of frames. You could check the input.

**Comment by Ciciluang** [comment]
thankyou very much.

**Comment by guoxigan** [comment]
> 

hi,there. I encountered a same problem with you.Have you solved this problem ? many thx

**Comment by guoxigan** [comment]
Maybe I konw how to solve the problem.Just uncomment the line code.
![image](https://user-images.githubusercontent.com/108337270/187951830-4c789f5e-dda1-45c6-ab81-cd67ed908910.png)
