### ISSUE TITLE
RuntimeError: result type Float can't be cast to the desired output type Long

### ISSUE THREAD

**Issue by bridgeqiqi** [SvipRepetitionCounting/TransRAC#11]
![image](https://user-images.githubusercontent.com/30117975/164968622-335eedb3-8089-43f8-8c98-44bf54930c3a.png)
The error will be thrown after training several epochs. Can anyone help to address the issue? Thank you!

**Comment by ZZYuting** [comment]
in normalize_label function add these:
this is author bug.
def normalize_label(y_frame, y_length):
    # y_length: total frames
    # return: normalize_label  size:nparray(y_length,)
    y_label = [0 for i in range(y_length)]  # 坐标轴长度，即帧数
    # ipdb.set_trace()
    for i in range(0, len(y_frame), 2):
        x_a = y_frame[i]
        x_b = y_frame[i + 1]
        avg = (x_b + x_a) / 2
        sig = (x_b - x_a) / 6
        num = x_b - x_a + 1  # 帧数量 update 1104
        if num != 1:
            for j in range(num):
                x_1 = x_a - 0.5 + j
                x_2 = x_a + 0.5 + j
                y_ing = get_integrate(x_1, x_2, avg, sig)
                if x_a + j >= len(y_label):
                    continue
                y_label[x_a + j] = y_ing
        else:
            y_label[x_a] = 1
    return y_label

**Comment by ZZYuting** [comment]
def normalize_label(y_frame, y_length):
    # y_length: total frames
    # return: normalize_label  size:nparray(y_length,)
    y_label = [0 for i in range(y_length)]  # 坐标轴长度，即帧数
    # ipdb.set_trace()
    for i in range(0, len(y_frame), 2):
        x_a = y_frame[i]
        x_b = y_frame[i + 1]
        avg = (x_b + x_a) / 2
        sig = (x_b - x_a) / 6
        num = x_b - x_a + 1  # 帧数量 update 1104
        if num != 1:
            for j in range(num):
                x_1 = x_a - 0.5 + j
                x_2 = x_a + 0.5 + j
                y_ing = get_integrate(x_1, x_2, avg, sig)
                if x_a + j >= len(y_label):
                    continue
                y_label[x_a + j] = y_ing
        else:
            y_label[x_a] = 1
    return y_label
