### ISSUE TITLE
What do the values in the L1, L2.... columns in the CSV file mean, and how to create the test.csv file

### ISSUE THREAD

**Issue by Ciciluang** [SvipRepetitionCounting/TransRAC#12]
I want to use my own data to test,but I don't know how to create the relative test.csv file

**Comment by ZYQbill** [comment]
Hi, @Ciciluang . the L1, L2... LN means the begining and the end frame for each action cycle. For example: L1 is the beginning frame index of the first action, L2 is the end frame index of the second action. [L3, L4] ... [Ln-1, Ln] are the same.
