### ISSUE TITLE
A runtime error occurred while training the model

### ISSUE THREAD

**Issue by Shellson** [SvipRepetitionCounting/TransRAC#15]
As I implemented this project, an error (**RuntimeError: result type Float can't be cast to the desired output type Long**) occurred during the training process. I've checked the code and found it had a problem while processing the sample with 0 repetition count. I want to ask whether you guys have met this problem before and are there any proper way to handle it. For now, I just delete all samples with 0 count and problem solved.

**Comment by bridgeqiqi** [comment]
> As I implemented this project, an error (**RuntimeError: result type Float can't be cast to the desired output type Long**) occurred during the training process. I've checked the code and found it had a problem while processing the sample with 0 repetition count. I want to ask whether you guys have met this problem before and are there any proper way to handle it. For now, I just delete all samples with 0 count and problem solved.

I have met the same problem. After deleting the samples with 0 count, it works.

**Comment by Ironieser** [comment]
Yep, so do we. For the counting task under this setting, we consider that the count of 0 (or others) is dirty data, and the preprocessing stage has done cleaning. But if we change the setting to others, we can be considered a hard case. So the released dataset retains this kind of data.

**Comment by Shellson** [comment]
Ok, I see, thanks!

**Comment by abcdvzz** [comment]
Hello guys, is the video with the count = 0 'stu6_44' only? I couldn't find any other videos with count=0. However, after I deleted it, I still get the same error.
