### ISSUE TITLE
Question about dataset

### ISSUE THREAD

**Issue by Shellson** [SvipRepetitionCounting/TransRAC#16]
In the test.csv file, the label of 'stu4_5.mp4' is bench_pressing with 51 repetition count, but in test file, the actual 'stu4_5.mp4' is the situp with 4 repetition count. Do you guys have this inconsistency?

**Comment by 957001934** [comment]
Oh! This is our mistake. We will soon fix this problem and recheck the whole dataset to prevent similar problems.

**Comment by Shellson** [comment]
Ok, could you make a notification here once you have updated the dataset? Thanks a lot!
