### ISSUE TITLE
Question on trained model

### ISSUE THREAD

**Issue by Shellson** [SvipRepetitionCounting/TransRAC#18]
Hi, there, I've loaded the trained model in the test.py, but I can not get consistent results illustrated in the paper (my MAE:0.61, OBO:0.18). Is there any setting I should notice when I apply this model?

**Comment by 957001934** [comment]
I'm sorry I can't help you with this problem. Generally, load our trained model, run the test.py, and you will get the result.
![0 44](https://user-images.githubusercontent.com/42710133/181263600-3ac54df5-22e3-44e1-9fa4-eb7b24d84821.jpg)

**Comment by guoxigan** [comment]
> Hi, there, I've loaded the trained model in the test.py, but I can not get consistent results illustrated in the paper (my MAE:0.61, OBO:0.18). Is there any setting I should notice when I apply this model?

Hi，I got a same results with you .Have you solve this problem?
![image](https://user-images.githubusercontent.com/108337270/187938368-c1255c40-acbe-429b-8726-58d2be3ab2d5.png)

**Comment by EMB310HH** [comment]
> > Hi, there, I've loaded the trained model in the test.py, but I can not get consistent results illustrated in the paper (my MAE:0.61, OBO:0.18). Is there any setting I should notice when I apply this model?
> 
> Hi，I got a same results with you .Have you solve this problem? ![image](https://user-images.githubusercontent.com/108337270/187938368-c1255c40-acbe-429b-8726-58d2be3ab2d5.png)

Hi，I got a same results with you .Have you solve this problem? But I haven't changed anything.
