### ISSUE TITLE
npz form datasets

### ISSUE THREAD

**Issue by isotopezzq** [SvipRepetitionCounting/TransRAC#22]
Hi! Is there any chance that you could release the processed npz files?
I used your public checkpoint and the released code to run test, and it turns out that there is still some mismatch between my results and the results from paper
![image](https://user-images.githubusercontent.com/63627336/187640349-820c645f-a968-4e8d-b68a-5ba169f62827.png)

**Comment by abcdvzz** [comment]
> 

Hello, could you please tell me how to download the videos? Maybe I can run some tests for you after that. Thank you.

**Comment by isotopezzq** [comment]
i didn't. i used the code in the project to convert the mp4 into npz

**Comment by abcdvzz** [comment]
Have u trained with the npz now? I trained with npz but with ~5% drop.

**Comment by zhao-yiqun** [comment]
I think such minor decay on MAE and OBO doesn't matter. Different CUDA, pytorch or even hardware may cause the mismatch
