### ISSUE TITLE
Test on UCFRep

### ISSUE THREAD

**Issue by guoxigan** [SvipRepetitionCounting/TransRAC#24]
Hi,there! I got a lower MAE and OBO comparer to the paper when I uesd your model ckpt to test on UCFRep dataset. Is there something wrong with me? Hope your help,thanks!

**Comment by ZYQbill** [comment]
Sorry for the late replay, maybe you can share more details and logs for your experiments

**Comment by isotopezzq** [comment]
I also want to test the model on UCFRep, but the UCFRep labels are not csv file.
![image](https://user-images.githubusercontent.com/63627336/195299171-a3f9d20d-c837-45a1-a0bc-004559fe468d.png)
Seems like you guys have reorganized the data, Can you tell me how to do it?
