### ISSUE TITLE
RuntimeError: result type Float can't be cast to the desired output type Long

### ISSUE THREAD

**Issue by Helen1p** [SvipRepetitionCounting/TransRAC#25]
Hello,I can't solve this problem after trying to delete the data 'stu6_44' ,and I met this problem in both npz/mp4 for many times ,do you guys know how to solve it ?Many thanks!
![ICF}6@J672EXK1E{_B8Y411](https://user-images.githubusercontent.com/115352228/194760595-da3778cf-c1fd-4cdb-930b-761a63ee16b1.png)

**Comment by isotopezzq** [comment]
you can set the dataloader num_worker=0

**Comment by Helen1p** [comment]
> 

Thanks, finally I deleted the train143.npz, stu9_67.npz, stu6_44.npz and it works ! Maybe caused by this 3 dirty data.
