### ISSUE TITLE
Question on test

### ISSUE THREAD

**Issue by guoxigan** [SvipRepetitionCounting/TransRAC#27]
hello! It'll output "predict_count" and "groundtruth" when I run the test.py, but some "groundtruth" can't match the value of count in test.csv(eg.I find '92' in test.csv, but I can't find that number in the list of "groundtruth"). Is it a bug?

**Comment by isotopezzq** [comment]
it is due to the process of label norm. IF the former cycle end in frame i and this cycle start in frame i, the number in the label will be rewrote in the position of frame i

**Comment by isotopezzq** [comment]
hey i wonder how did you test on the UCFRep, can you give me some instructions?

**Comment by guoxigan** [comment]
> hey i wonder how did you test on the UCFRep, can you give me some instructions?

I just used the code released by the author
![image](https://user-images.githubusercontent.com/108337270/195328131-6fbb863c-ba58-4584-a4b7-12ebe7294080.png)

**Comment by isotopezzq** [comment]
but where do you get the ucfval.csv

**Comment by guoxigan** [comment]
> it is due to the process of label norm. IF the former cycle end in frame i and this cycle start in frame i, the number in the label will be rewrote in the position of frame i in ./dataset/labelnorm.py ![image](https://user-images.githubusercontent.com/63627336/195311919-777de68c-a1d9-40a4-b020-588cf0e849a7.png) if you change the line into += and the label will match

I know that.I mean the some value of 'count' in line 38 doesn't match the value of 'count' in test.csv 
![image](https://user-images.githubusercontent.com/108337270/195330599-5f93784d-2023-4ec5-a151-f1361c151f2b.png)

**Comment by guoxigan** [comment]
> but where do you get the ucfval.csv

I get the UCFRep's infomation from the paper named "Context-aware and Scale-insensitive Temporal Repetition Counting", and i made the ucfval.csv

**Comment by guoxigan** [comment]
> 留个联系方式吧，这里说的太麻烦

vx 18801013532

**Comment by EMB310HH** [comment]
> > it is due to the process of label norm. IF the former cycle end in frame i and this cycle start in frame i, the number in the label will be rewrote in the position of frame i in ./dataset/labelnorm.py ![image](https://user-images.githubusercontent.com/63627336/195311919-777de68c-a1d9-40a4-b020-588cf0e849a7.png) if you change the line into += and the label will match
> 
> I know that.I mean some value of 'count' in line 38 doesn't match the value of 'count' in test.csv ![image](https://user-images.githubusercontent.com/108337270/195330599-5f93784d-2023-4ec5-a151-f1361c151f2b.png)

Hi. I also noticed this problem. In doing so, the author only compared the true value of the generated tag, not the real count value.

**Comment by EMB310HH** [comment]
> hello! It'll output "predict_count" and "groundtruth" when I run the test.py, but some "groundtruth" can't match the value of count in test.csv(eg.I find '92' in test.csv, but I can't find that number in the list of "groundtruth"). Is it a bug?

In addition, I noticed that you said that the results of running the public trained weight were (MAE: 0.61, OBO: 0.18), and I got the same results as you. Have you solved it? Would it be convenient to tell me the solution.thx

**Comment by 957001934** [comment]
> In addition, I noticed that you said that the results of running the public trained weight were (MAE: 0.61, OBO: 0.18), and I got the same results as you. Have you solved it? Would it be convenient to tell me the solution.thx

Maybe your data process has some problem.
![0 44](https://user-images.githubusercontent.com/42710133/195770978-0c0f88ea-41f1-4fd3-9b86-6d9461df97bb.jpg)

**Comment by guoxigan** [comment]
> > hello! It'll output "predict_count" and "groundtruth" when I run the test.py, but some "groundtruth" can't match the value of count in test.csv(eg.I find '92' in test.csv, but I can't find that number in the list of "groundtruth"). Is it a bug?
> 
> In addition, I noticed that you said that the results of running the public trained weight were (MAE: 0.61, OBO: 0.18), and I got the same results as you. Have you solved it? Would it be convenient to tell me the solution.thx

you should try to transform .mp4 to .npz
