### ISSUE TITLE
Can't get the similar result in the paper

### ISSUE THREAD

**Issue by Helen1p** [SvipRepetitionCounting/TransRAC#29]
Hi, guys, I've trained the model by running train.py, then loaded the checkpoint of epoch 198 in  test.py, but I can not get consistent results illustrated in the paper. Is there any setting I should change ? Please tell me the problem. many thanks!
![82N _0J2B6X_P76H(}07QXP](https://user-images.githubusercontent.com/115352228/197134103-089840a0-d3f7-4b81-b7c3-ea5a53cfbe4e.png)

**Comment by 957001934** [comment]
you should try to transform .mp4 to .npz
