### ISSUE TITLE
Could you provide your paper, pls

### ISSUE THREAD

**Issue by ZZYuting** [SvipRepetitionCounting/TransRAC#3]
I can't find your paper, could you pls provide your paper?Thanks a lot.

**Comment by Ironieser** [comment]
Sry, we are adding more details to the paper, which will upload to arXiv soon.

**Comment by ZZYuting** [comment]
> Sry, we are adding more details to the paper, which will upload to arXiv soon.
Thanks, Could you give your benchmark or experiments firstly? I'm interesting about it.  Also,  Which methods do you compare with?

**Comment by ZYQbill** [comment]
> > Sry, we are adding more details to the paper, which will upload to arXiv soon.
> > Thanks, Could you give your benchmark or experiments firstly? I'm interesting about it.  Also,  Which methods do you compare with?

The benchmarks was provided on the homepage, please refer to [homepage]( https://svip-lab.github.io/dataset/RepCount_dataset.html). The arxiv preprint will be published in few days.

**Comment by ZYQbill** [comment]
> > Sry, we are adding more details to the paper, which will upload to arXiv soon.
> > Thanks, Could you give your benchmark or experiments firstly? I'm interesting about it.  Also,  Which methods do you compare with?

Hi, The preprint is published at [arxiv](https://arxiv.org/abs/2204.01018). If you have any other problems, don't hesitate to open a new issue.
