### ISSUE TITLE
Using the published code, cannot get the same results as in the paper.

### ISSUE THREAD

**Issue by yanrbrave** [SvipRepetitionCounting/TransRAC#31]
Using your published code and ckpt to test on the RepcountA dataset, you cannot get the same results as in the paper. Is there anything that needs to be adjusted?

**Comment by 957001934** [comment]
you should try to transform .mp4 to .npz
![image](https://user-images.githubusercontent.com/42710133/199384437-f296aa25-033c-4d25-a7ce-0cf2f139ff47.png)
