### ISSUE TITLE
have question about the training process  

### ISSUE THREAD

**Issue by hugski** [SvipRepetitionCounting/TransRAC#35]
In dataloader, it "select 64 frames from total original frames, proportionally" in every video sequence, but how to predict the total count with only 64 frames?
for example, in a situp video, if the sampled 64 frames are all "sit" state by coincidence, then we can infer the count is 0, while the ground truth is not

**Comment by ZYQbill** [comment]
Sorry for the late reply.

This is a limitation of our methods, we have discussed this in our paper. 

The 64 frame samples are follow the frame selection of the former work RepNet(CVPR20). 

If you have any other questions about TransRAC, feel free to reopen the issue.
