### ISSUE TITLE
Not able to reproduce results

### ISSUE THREAD

**Issue by YaqoobD** [SvipRepetitionCounting/TransRAC#40]
Dear Authors,
I have tried to reproduce the results with the provided implementations, but unfortunately, I am not able to reproduce the result below is not code:
import os
from dataset.RepCountA_raw_Loader import MyData
from models.TransRAC import TransferModel
from testing.test_looping import test_loop
import matplotlib.pyplot as plt

N_GPU = 1
device_ids = [i for i in range(N_GPU)]
os.environ["CUDA_VISIBLE_DEVICES"] = "0"

root_path = r'C:\Users\TestUser\OneDrive - Lovehoney Group\Desktop\Master_thesis\TransRAC\LLSP_dataset'

test_video_dir = r'video\test'
test_label_dir = r'annotation\test.csv'

config = './configs/recognition/swin/swin_tiny_patch244_window877_kinetics400_1k.py'
checkpoint = './pretrained/swin_tiny_patch244_window877_kinetics400_1k.pth'
lastckpt = None

print("path:", test_label_dir)

NUM_FRAME = 64
SCALES = [1, 4, 8]
test_dataset = MyData(root_path, test_video_dir, test_label_dir, num_frame=NUM_FRAME)
my_model = TransferModel(config=config, checkpoint=checkpoint, num_frames=NUM_FRAME, scales=SCALES, OPEN=False)
NUM_EPOCHS = 1
test_loop(NUM_EPOCHS, my_model, test_dataset, lastckpt=lastckpt)
![image](https://user-images.githubusercontent.com/52135942/217840020-cc590088-6b9d-459b-9d51-43b1825502ee.png)

Furthermore, my results are negative, and my MAE and OBO are also very low.

![image](https://user-images.githubusercontent.com/52135942/217840218-f8a50ab2-5e1d-4e1b-a785-8cbe96f78c1a.png)

It would great if  you could provide your take on this.

**Comment by ZYQbill** [comment]
Hi,

This problem is unexceptional,  maybe you can refer to this issue [issues](https://github.com/SvipRepetitionCounting/TransRAC/issues/27) and transform .mp4 to .npz.
