### ISSUE TITLE
the way to use the given pretrained weights 

### ISSUE THREAD

**Issue by whuyyc** [SvipRepetitionCounting/TransRAC#42]
hello! could you please tell me how to use the checkpoint you provide? 
![71OU}Q$ZFESNFAJ~PTYH}UV](https://user-images.githubusercontent.com/52364175/222172215-60cf94a2-952b-45ad-b93d-224f6f683872.png)
I have downloaded the checkpoint "transrac_ckpt_pytorch_171.pt", but when I used it in the test.py, it required the corresponding config. I did not find the file that match the "transrac_ckpt_pytorch_171" in ./configs/.

**Comment by fy916** [comment]
I guess you can put the checkpoint anywhere and it should be set in the file "test.py" at around line 28, where you change the line "lastckpt = None" to "lastckpt = transrac_ckpt_pytorch_171 directory"

**Comment by whuyyc** [comment]
Thanks a lot!

> I guess you can put the checkpoint anywhere and it should be set in the file "test.py" at around line 28, where you change the line "lastckpt = None" to "lastckpt = transrac_ckpt_pytorch_171 directory"
