### ISSUE TITLE
128 frame scale error:RuntimeError: Calculated padded input size per channel: (0 x 224 x 224). Kernel size: (2 x 4 x 4). Kernel size can't be greater than actual input size

### ISSUE THREAD

**Issue by hchen-MST** [SvipRepetitionCounting/TransRAC#47]
I read the paper and would like to check the model on 128 frame scale since the paper mentioned a larger scale yields a better performance, but I got an error like:
 
RuntimeError: Calculated padded input size per channel: (0 x 224 x 224). Kernel size: (2 x 4 x 4). Kernel size can't be greater than actual input size

**Comment by DanielC-MST** [comment]
Is that because of the video 2 npz?

**Comment by Ironieser** [comment]
Please try to refer to #43 and adjust the num of frames or check the input data.

**Comment by ZYQbill** [comment]
Close as no update.
