### ISSUE TITLE
what frames and frames_length means

### ISSUE THREAD

**Issue by Y-Claw** [SvipRepetitionCounting/TransRAC#5]
Because data process  script is not provided, so I'm not sure what data should store in npz file.
in TransRAC/dataset/RepCountA_Loader.py function get_frames:
    frames = data['imgs']  # numpy.narray
    frames_length = data['fps'].item()
Is 'frames' 64 frames sampled from origin video and size 224*224 and 'frames_length' origin video total frame number?

**Comment by 957001934** [comment]
For npz files, no worry, we will upload them soon.
I am sorry, the name of variable is confusing. We have renamed them and add more annotation.
Now, you can use the 'RepCountA_raw_Loader.py ' to load the data from origin video.
There are one frame array ([64, 3,224, 224]) and the total number of original video frames in npz file.
I hope the above can help you.
