### ISSUE TITLE
frame length error

### ISSUE THREAD

**Issue by ProvenceStar** [SvipRepetitionCounting/TransRAC#50]
When I try to make use of the video frame length parameter obtained from get_frames function, I noticed that the frame length of some videos do not match, for example in stu1_10.npz, I get a total frame length of about 1600 but found that it has a count label in 1840 frames, can you fix this problem? It seems that video2npz does not work fine, thank you.

**Comment by ZYQbill** [comment]
The video2npz works fine. Some label may be missmatched. you can simply delete them.
