### ISSUE TITLE
Missing label2rep?

### ISSUE THREAD

**Issue by stefanoalletto** [SvipRepetitionCounting/TransRAC#55]
Hi folks, I'm trying to reproduce your results and reading the various issues looks like I'd get better numbers by first converting to npz. The script you have to do so fails at [this line](https://github.com/SvipRepetitionCounting/TransRAC/blob/00f8954d484a37088ee02131b65f460b01388feb/tools/video2npz.py#L9) when trying to import label2rep. A quick search in the repo doesn't show a script with that name, any ideas?

Thanks

**Comment by Ironieser** [comment]
Hi, 
It's a useless line of code and pls delete it.
We will update the code.
Thx
