### ISSUE TITLE
Comparison with other methods.

### ISSUE THREAD

**Issue by salute-hh** [SvipRepetitionCounting/TransRAC#61]
Since there is no publicly available training code for RepNet [5], are the results of RepNet [5] in RepCount in your paper obtained by you reproduce RepNet? Or did you just use the publicly available weights of RepNet [5] for testing on RepCount? Looking forward to your reply! Thanks!

**Comment by HuazhangHu** [comment]
The source code of RepNet is implemented with tensorflow. However, they only open the inference code, don't open the training code. Besides, the weight of RepNet is not open. So we reproduce RepNet using pytorch according to the open source code.

**Comment by salute-hh** [comment]
I would like to ask if this part of the code can be shared so that there is no deviation between the comparison methods and the indicators reported in your paper.
