### ISSUE TITLE
Code of comparison with sota models

### ISSUE THREAD

**Issue by howell0203** [SvipRepetitionCounting/TransRAC#62]
thank u for your paper and code, could provide the comparison code to count the MAE and OBO in ur paper, like X3D [7], Video SwinT [23] ,Zhang et al. [39]. THANK YOU VERY MUCH!

**Comment by jokingww** [comment]
Great Work! I want to know how to adpot X3d[7] to a frame-level detection method. Can you please expalin how to make it?

**Comment by HuazhangHu** [comment]
> Great Work! I want to know how to adpot X3d[7] to a frame-level detection method. Can you please expalin how to make it?
We use X3D[7]  as the vision backbone, which playing the role of a feature extraction module.  You can try to replace the VideoSwin Transformer module with X3D model.

**Comment by HuazhangHu** [comment]
> Great Work! I want to know how to adpot X3d[7] to a frame-level detection method. Can you please expalin how to make it?

We use X3D[7]  as the vision backbone, which playing the role of a feature extraction module.  You can try to replace the VideoSwin Transformer module with X3D model.
